version: '3.8'

services:
  app:
    build:
      context: ./API-BlackJackFinder
    volumes:
      - ./API-BlackJackFinder:/usr/src/app
      - ./API-BlackJackFinder/var:/usr/src/app/var
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

volumes:
  db_data:
